
  export const NOW_PLAYING_API_ENDPOINT = "/.netlify/functions/nowplaying"
  export const TRENDING_MOVIE_API_ENDPOINT = "/.netlify/functions/trending"
  export const VIDEO_API_ENDPOINT = "/.netlify/functions/video"
  export const SEARCH_MOVIE_API_ENDPOINT = "/.netlify/functions/searchmovie"
  export const YOUTUBE_LINK = "https://www.youtube.com/embed/"
  export const YOUTUBE_LINK_SUFFIX = "?autoplay=1&mute=1"
  export const HERO_TYPE = "Trailer"
  export const IMAGE_PATH = "https://image.tmdb.org/t/p/w185/"
  export const SEARCHAPI_ENDPOINT = "/.netlify/functions/openAI"